meta_product_name: "sart"
meta_title: "s.art - Every story, one search away..."
meta_description: "Film search site, to find where to watch your favorite movies!"
meta_image: "cover.png" # should exist in `app/assets/images/`
